### ISSUE TITLE
Problems with building from source 

### ISSUE THREAD

**Issue by philschulz** [awslabs/sockeye#141] opened 2017-09-14 09:13 UTC
When I try to build from source using "python setup.py install -r requirements.gpu-cu80.txt" I get the following error:

Searching for mxnet-cu80==0.10.0
Reading https://pypi.python.org/simple/mxnet-cu80/
No local packages or working download links found for mxnet-cu80==0.10.0
error: Could not find suitable distribution for Requirement.parse('mxnet-cu80==0.10.0')

However, typing "pip install mxnet-cu80==0.10.0" solves that problem.

Next, when I run "pip install -e '.[optional]'" the command fails on the first attempt with the following output:

Obtaining file:///home/pschulz/sockeye
Collecting pyyaml (from sockeye==1.7.1)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 5.9MB/s 
Collecting mxnet==0.10.0 (from sockeye==1.7.1)
  Using cached mxnet-0.10.0-py2.py3-none-manylinux1_x86_64.whl
Requirement already satisfied: numpy>=1.12 in /home/pschulz/toy-env/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-x86_64.egg (from sockeye==1.7.1)
Collecting tensorboard (from sockeye==1.7.1)
  Using cached tensorboard-1.0.0a6-cp36-cp36m-manylinux1_x86_64.whl
Collecting matplotlib (from sockeye==1.7.1)
  Using cached matplotlib-2.0.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting werkzeug>=0.11.10 (from tensorboard->sockeye==1.7.1)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Requirement already satisfied: wheel>=0.26 in /home/pschulz/toy-env/lib/python3.6/site-packages (from tensorboard->sockeye==1.7.1)
Collecting six>=1.10.0 (from tensorboard->sockeye==1.7.1)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting Pillow>=4.0.0 (from tensorboard->sockeye==1.7.1)
  Using cached Pillow-4.2.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting protobuf>=3.1.0 (from tensorboard->sockeye==1.7.1)
  Using cached protobuf-3.4.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting pytz (from matplotlib->sockeye==1.7.1)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib->sockeye==1.7.1)
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 (from matplotlib->sockeye==1.7.1)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting python-dateutil (from matplotlib->sockeye==1.7.1)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting olefile (from Pillow>=4.0.0->tensorboard->sockeye==1.7.1)
Requirement already satisfied: setuptools in /home/pschulz/toy-env/lib/python3.6/site-packages (from protobuf>=3.1.0->tensorboard->sockeye==1.7.1)
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: /home/pschulz/.cache/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
Successfully built pyyaml
Installing collected packages: pyyaml, mxnet, werkzeug, six, olefile, Pillow, protobuf, tensorboard, pytz, cycler, pyparsing, python-dateutil, matplotlib, sockeye
  Found existing installation: sockeye 1.7.1
    Uninstalling sockeye-1.7.1:
      Successfully uninstalled sockeye-1.7.1
  Running setup.py develop for sockeye
Successfully installed Pillow-4.2.1 cycler-0.10.0 matplotlib-2.0.2 mxnet-0.10.0 olefile-0.44 protobuf-3.4.0 pyparsing-2.2.0 python-dateutil-2.6.1 pytz-2017.2 pyyaml-3.12 six-1.10.0 sockeye tensorboard-1.0.0a6 werkzeug-0.12.2
Traceback (most recent call last):
  File "/home/pschulz/toy-env/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/pschulz/toy-env/lib/python3.6/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/home/pschulz/toy-env/lib/python3.6/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/home/pschulz/toy-env/lib/python3.6/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/home/pschulz/toy-env/lib/python3.6/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/home/pschulz/toy-env/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/home/pschulz/toy-env/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/pschulz/toy-env/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/home/pschulz/toy-env/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/home/pschulz/toy-env/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/home/pschulz/toy-env/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/home/pschulz/toy-env/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/pschulz/toy-env/lib/python3.6/site-packages/sockeye-1.7.1-py3.6.egg'

It does, however, succeed, when I run it a second time. Any idea where this problem might stem from?

Thanks a lot in advance.

**Comment by tdomhan** [comment] 2017-09-14 09:21
interesting. I'm not sure exactly where this problem is coming from. The system you're installing sockeye on is a linux system?

**Comment by philschulz** [comment] 2017-09-14 09:25
Yes, I think centos is on our servers. Here's the proc/version content:

Linux version 4.4.0-79-generic (buildd@lcy01-30) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

**Comment by philschulz** [comment] 2017-09-14 09:27
Actually, forget what I wrote before. It's Ubuntu that we're running.

**Comment by tdomhan** [comment] 2017-09-15 16:46
It's strange that pip will be able to install successfully, but taking the same version from the requirements.txt fails. I can reproduce the issue in a new miniconda environment. You're able to install and use Sockeye, right?
In any case, I'll try to investigate what's going on here. In the meantime just installing all requirements (`pyaml, numpy, mxnet`) manually and then running `python setup.py install --no-deps` should work fine.

**Comment by philschulz** [comment] 2017-09-17 12:42
Yes, installing and using it is no problem for me. The main issue is that I want to make it easily accessible to other people in my group by providing installation scripts/ducttape workflows. Those should ideally be black box/ run without trouble. Thanks for looking into this!

**Comment by tdomhan** [comment] 2017-09-18 11:35
makes sense. Until we figure this out something like:
```
conda install numpy # or: pip install numpy
pip install mxnet-cu80
pip install pyaml
python setup.py install --no-deps
```
should probably be the best bet. If this is scripted it shouldn't be too big of an issue. Other alternative: docker ;)
Anyway, I'll let you know when I find out what's going on here.

**Comment by philschulz** [comment] 2017-09-18 12:27
Yep, I've changed the script that way. Still need to learn Docker, though ;)

**Comment by tdomhan** [comment] 2017-09-18 16:46
it basically solves all these problems (and gives you other problems to solve ;)). Essentially you can just convert the script you created into a Dockerfile, which is a reproducible recipe for creating docker images with sockeye (+ dependencies) setup correctly.

**Comment by philschulz** [comment] 2017-10-09 07:30
Hey there,

the problem seems to have become a more general one. I just started working on a new machine and now it's not even possible anymore to install money 0.10.0. I have install python 3.6.3 using brew. When I type "pip install mxnet=0.10.0" I get the following:
Could not find a version that satisfies the requirement mxnet==0.10.0 (from versions: 0.9.5, 0.11.0b20170815, 0.11.0b20170816, 0.11.0b20170817, 0.11.0b20170818, 0.11.0b20170819, 0.11.0b20170820, 0.11.0b20170821, 0.11.0rc3, 0.11.0, 0.11.1b20170822, 0.11.1b20170823, 0.11.1b20170824, 0.11.1b20170825, 0.11.1b20170826, 0.11.1b20170827, 0.11.1b20170828, 0.11.1b20170829, 0.11.1b20170901, 0.11.1b20170902, 0.11.1b20170903, 0.11.1b20170904, 0.11.1b20170905, 0.11.1b20170906, 0.11.1b20170907, 0.11.1b20170908, 0.11.1b20170909, 0.11.1b20170910, 0.11.1b20170911, 0.11.1b20170912, 0.11.1b20170913, 0.11.1b20170914, 0.11.1b20170915, 0.11.1b20170916, 0.11.1b20170917, 0.11.1b20170918, 0.11.1b20170919, 0.11.1b20170920, 0.11.1b20170921, 0.11.1b20170922, 0.11.1b20170923, 0.11.1b20170924, 0.11.1b20170925, 0.11.1b20170926, 0.11.1b20170927, 0.11.1b20170928, 0.11.1b20170929, 0.11.1b20170930, 0.11.1b20171001, 0.11.1b20171002, 0.11.1b20171003, 0.11.1b20171004, 0.11.1b20171005, 0.11.1b20171006, 0.11.1b20171007)
No matching distribution found for mxnet==0.10.0

It's strange that it still has 0.9.5 but not 10. Not sure if you can do anything about this but still wanted to point it out.

**Comment by tdomhan** [comment] 2017-10-09 09:01
yeah,that's unfortunate. We'd like to move to 0.11 asap, but there's currently one remaining blocker that we fixed, but needs to make it into a released version. Looking at pypi it looks like 0.10.0 was removed, but there's a version 0.10.0.post, so `pip install mxnet==0.10.0.post2` should work. Does this work for you?

**Comment by philschulz** [comment] 2017-10-10 22:41
No,

unfortunately it did not work. Maybe it's because I'm using Python-3.6.3? Anyhow, I can just wait until you guys move to mxnet11. Most of the machines that I am using already have mxnet10 installed.

**Comment by fhieber** [comment] 2017-11-02 07:42
Closing since we moved to mxnet-12 now.

**Closed by fhieber** 2017-11-02 07:42 UTC

**Comment by tdomhan** [comment] 2017-11-09 12:55
so it actually turns out that mxnet only exists as in the `wheel` package format, which is not supported by setuptools. So `python setup.py install` will always fail unless mxnet has already been installed manually. The workaround is to use `pip install .` instead, as `pip` understands the `wheel` package format.
