### ISSUE TITLE
--max-seq-length not used for inference

### ISSUE THREAD

**Issue by jeremiedb** [awslabs/sockeye#182] opened 2017-11-03 19:30 UTC
It appears that max-seq-length is no longer transfered to --max-input-len of the inference arguments when tracking the BLEU on transformer encoder-decoder model. The log below shows that inference buckets up to a length of 1540 are created which resulted in an error for tracking BLEU, although the training process continued on normal buckets length of 80 as expected from the parameter --max-seq-length 80. 
The BLEU tracking works properly for both rnn and cnn configurations. 

```
/sockeye/model_fr_en_trans/params.00006"
[INFO:sockeye.inference] Translator (1 model(s) beam_size=5 ensemble_mode=None batch_size=16 buckets_source=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950] buckets_target=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980, 990, 1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1080, 1090, 1100, 1110, 1120, 1130, 1140, 1150, 1160, 1170, 1180, 1190, 1200, 1210, 1220, 1230, 1240, 1250, 1260, 1270, 1280, 1290, 1300, 1310, 1320, 1330, 1340, 1350, 1360, 1370, 1380, 1390, 1400, 1410, 1420, 1430, 1440, 1450, 1460, 1470, 1480, 1490, 1500, 1510, 1520, 1530, 1540])
[17:55:25] /mxnet/dmlc-core/include/dmlc/./logging.h:308: [17:55:25] src/storage/./pooled_storage_manager.h:102: cudaMalloc failed: out of memory
```

**Comment by fhieber** [comment] 2017-11-04 09:44
Thanks for submitting this issue, I will take a look on Monday!

**Comment by fhieber** [comment] 2017-11-06 08:55
@jeremiedb I think I found the issue. #184 should fix it.

**Comment by fhieber** [comment] 2017-11-06 12:37
I am closing this for now. Feel free to reopen if the problem persists.

**Comment by jeremiedb** [comment] 2017-11-07 01:38
Thanks for the quick fix. I'm afraid though something else has been broken in the process as the validation perplexity is now skyrocketing, resulting in an early stop of the training.

```
[INFO:sockeye.training] Checkpoint [2]	Train-perplexity=18.410813
[INFO:sockeye.training] Checkpoint [2]	Validation-perplexity=240866.669866
[INFO:sockeye.callback] Checkpoint [1]: Decoder finished ({'avg-sec-per-sent-val': 0.4793375844955444, 'bleu-val': 0.09351544932873244})
```

This behavior is now observed for all types of model (cnn and transformer tested). The perplexity on train and eval used to be more coherent, yet the BLEU seem to behave appropriately. 

Not sure if it's related, but I found the following bucketing setup suspect as I would have expect source and target to share the same number of buckets: 

`[INFO:sockeye.inference] Translator (1 model(s) beam_size=5 ensemble_mode=None batch_size=16 buckets_source=[10, 20, 23] buckets_target=[10, 20, 30, 40, 49])`

**Comment by fhieber** [comment] 2017-11-07 07:14
Could you post your training command and the log here? Are you using a special kind of data with very different source/target lengths? The line in your post above seems fine in that it says that your maximum observed source length or input_length is 23 tokens and we allow output lengths for
```
output_length = int(np.ceil(factor * input_length))
```
where `factor` is 
```
max_mean + (max_std * num_stds)
```
`max_mean` is the mean target/source length ratio observed in the training data ('max' because we find the maximum value if multiple models are loaded for ensembling), and `max_std=2` by default.
Disregarding the `ceil()`, your mean length ratio + 2 std (factor) should be around
```
49/23 = 2.13
```
which says that your target side data is on average twice as long as your input.

**Comment by fhieber** [comment] 2017-11-07 08:07
#186 should solve the high validation perplexity issue

**Comment by fhieber** [comment] 2017-11-08 16:56
Closing this once more, feel free to reopen if the issue is not resolved.

**Closed by fhieber** 2017-11-08 16:56 UTC
