### ISSUE TITLE
Misalignment of translations

### ISSUE THREAD

**Issue by xingniu** [awslabs/sockeye#477] opened 2018-07-16 03:59 UTC
It was not a problem before, but I recently find that there is misalignment (of lines) between the input and the translation output when chunk-size > 1. For example,
- chunk-size=1024, batch-size=16 (misaligned)
- chunk-size=1024, batch-size=1 (misaligned)
- chunk-size=1, batch-size=1 (aligned)

It doesn't always happen, so I haven't found out how it's triggered. I observe this situation when translating large documents (which usually contain empty lines).

**Comment by artemsok** [comment] 2018-07-17 09:52
Can you share a dataset where we could reproduce the issue?

**Comment by tdomhan** [comment] 2018-07-19 06:41
thanks for reporting! We will look into this. In the mean time let us know if you have any additional information. For example:
* How large is the test set?
* Did you feed inputs and outputs via stdin/stdout or through files?

**Comment by tdomhan** [comment] 2018-07-19 06:58
or if you had an example based on the [sequence copy](https://github.com/awslabs/sockeye/tree/master/tutorials/seqcopy) task that reproduces this issue it would also be great.

**Comment by xingniu** [comment] 2018-07-19 12:54
It's a third-party dataset so I cannot share it directly.  The files causing this problem have around 1,300 lines, which is larger than the chunk-size=1024. 24% lines are blank.
I haven't got a chance to do a diagnostic toy test that could reproduces this issue.

**Comment by artemsok** [comment] 2018-07-19 14:20
Would you be able to reproduce and share an obfuscated version of your dataset with every word replaced by its vocabulary id (or maybe even just a fixed token)?

**Comment by fhieber** [comment] 2018-07-19 15:15
another relevant question: are you setting a specific maximum output length, or is your model imposing one (e.g. its using learned positional embeddings)? What I am getting at is whether the input sentences are split into multiple chunks or not (i.e. are there exactly 1300 requests, split in chunks of 1024, or more).

**Comment by xingniu** [comment] 2018-07-19 15:44
You can find a obfuscated sample [here](https://obj.umiacs.umd.edu/mt-data/input.00.id). I set --max-seq-len=81:80 and I think there's sentences longer than 81 tokens in the sample. I used a RNN model and I didn't use learned positional embeddings.

**Comment by artemsok** [comment] 2018-07-24 08:54
Thanks. I was able to reproduce this, will debug more.

**Comment by artemsok** [comment] 2018-07-24 13:22
@mjpost No, the default sorting behavior work just like that.

I think the bug was in the empty sentence handling, see #488 

@xingniu Could you try the fix (just 3 lines to edit), and let us know if this solves the problem with your data? On the obfuscated file I now get the same outputs.

**Comment by xingniu** [comment] 2018-07-24 13:58
Yes, it works. Thanks!

**Comment by tdomhan** [comment] 2018-07-25 14:37
thanks for looking into this @artemsok. 

@mjpost this works because tuples are sorted by their members in order in python.So the output will be sorted by sentence id and then by chunk id.

Closing the issue as this seems fixed.

**Closed by tdomhan** 2018-07-25 14:37 UTC
