### ISSUE TITLE
Debugging Sockeye Extensions

### ISSUE THREAD

**Issue by anjishnu** [awslabs/sockeye#310] opened 2018-03-02 16:01 UTC
What is the best way to debug the mxnet symbolic API (e.g. tensor shapes) during development. 
One idea I have heard some people recommend is to swap out the entire symbolic API for the ndarray API, during debugging - is there a better way to go about this?

If this is a common use case, does it make sense to modify Sockeye so that swapping symbolic and imperative interfaces is relatively straightforward?

**Comment by fhieber** [comment] 2018-03-02 16:08
Yeah, debugging is not easy with the symbolic API.
Usually shape inference problems can be hunted down quite well with carefully naming operators so it becomes clear where the problem is.
The idea of swapping `sym` with `nd` sounds interesting, but I am not sure it would work in the case of Sockeye. In any case, that sounds very much like Gluon/HybridBlocks, no?

**Comment by fhieber** [comment] 2018-03-02 16:11
If you have a working graph and want to look at values flowing through it, you may find the PrintValue operator useful: https://github.com/awslabs/sockeye/blob/5dcb60da8767fe7c667b8073e19574d10c2bb84f/sockeye/utils.py#L715

**Comment by anjishnu** [comment] 2018-03-02 17:20
Yes, you are right, Gluon HybridBlocks are explicitly designed to keep the APIs abstracted - so debugging just means running it with a 'different backend'.  Thanks for the operator, it is definitely helpful, for one of the common problems at least.

**Comment by fhieber** [comment] 2018-03-05 15:53
Closing, feel free to reopen if you have more questions on this!

**Closed by fhieber** 2018-03-05 15:53 UTC
