### ISSUE TITLE
Problem with multiprocessing context

### ISSUE THREAD

**Issue by adamkusmirek** [awslabs/sockeye#684] opened 2019-04-23 13:26 UTC
I am currently experiencing the following issue when running `sockeye-train`:
```
[INFO:sockeye.training] Training started.
[INFO:sockeye.utils] Releasing GPU 0.
[ERROR:root] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/bin/sockeye-train", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/sockeye/train.py", line 825, in main
    train(args)
  File "/usr/local/lib/python3.6/dist-packages/sockeye/train.py", line 955, in train
    existing_parameters=args.params)
  File "/usr/local/lib/python3.6/dist-packages/sockeye/training.py", line 627, in fit
    process_manager = DecoderProcessManager(self.model.output_dir, decoder=decoder)
  File "/usr/local/lib/python3.6/dist-packages/sockeye/training.py", line 1282, in __init__
    self.ctx = mp_utils.get_context()  # type: ignore
  File "/usr/local/lib/python3.6/dist-packages/sockeye/multiprocessing_utils.py", line 71, in get_context
    assert __context is not None, ("Multiprocessing context not initialized. Please call "
AssertionError: Multiprocessing context not initialized. Please call sockeye.multiprocessing_utils.initialize() right after interpreter startup.
```
Any idea what could be causing this?

I am running sockeye using mxnet-cu100mkl inside a singularity container.

**Comment by fhieber** [comment] 2019-04-24 08:03
Thanks for reporting. I am not sure what the problem is. `sockeye.train` calls `mp.initialize()` right at start up. Are you using that module somehow in your own script? What is a singularity container?

**Comment by adamkusmirek** [comment] 2019-04-24 11:36
> Thanks for reporting. I am not sure what the problem is. `sockeye.train` calls `mp.initialize()` right at start up. 

That's what confused me too after having a look at the source.

> Are you using that module somehow in your own script?
I am calling the module inside a bash script:
```
sockeye-train -d ${TRAIN_DATA_DIR} \
              -vs ${SRC_CORP} \
              -vt ${TGT_CORP} \
              --encoder rnn \
              --decoder rnn \
              --num-embed 256 \
              --rnn-num_hidden 512 \
              --rnn-attention-type dot \
              --max-seq-len 60 \
              --decode-and-evaluate 500 \
              -o ${MODEL_DIR}
```
Basically I have been following the WMT tutorial.

> What is a singularity container?

Ah sorry, it's a container platform comparable to Docker: https://www.sylabs.io/singularity/

**Comment by tdomhan** [comment] 2019-05-06 13:37
This is strange indeed. Do you see any of the following in the logs:
```
Semphore tracker and forkserver started.
Forkserver spawn method not available. Default spawn method will be used.
Multiprocessing context not initialized. Please call sockeye.multiprocessing_utils.initialize() right after interpreter startup.
```

We do check for `if __name__ == "__main__":` in `train.py`. Could it be that when running the generated cli script `sockeye-train` the `train.py` is not considered `__main__`?

**Comment by tdomhan** [comment] 2019-05-10 20:11
btw, running `python -m sockeye.train` should unblock you for now.

**Comment by jamesewoo** [comment] 2019-07-01 16:31
> Could it be that when running the generated cli script `sockeye-train` the `train.py` is not considered `__main__`?

I think this is the case. If you look at `setup.py` it points directly to `sockeye.train:main`.

Since the multiprocessing init method checks if it's already been called, could you simply remove the `if` condition?

**Comment by tdomhan** [comment] 2019-07-07 02:37
I think you're completely right. I created a small PR changing the behavior: https://github.com/awslabs/sockeye/pull/704

**Comment by fhieber** [comment] 2019-07-09 11:20
#704 was merged.

**Closed by fhieber** 2019-07-09 11:20 UTC
