### ISSUE TITLE
sockeye gpu locking incompatible with $CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by rudinger** [awslabs/sockeye#391] opened 2018-05-11 14:26 UTC
It appears that sockeye's default gpu locking behavior is incompatible with `CUDA_VISIBLE_DEVICES` being set. Here's an example of two independently scheduled sockeye jobs running on the same machine, with `CUDA_VISIBLE_DEVICES` set:

```
# Job 1, cluster assigns GPU 2
export CUDA_VISIBLE_DEVICES=2
python -m sockeye.train .... --device-ids 0
# Sockeye is now running on absolute gpu 2 but it thinks its training on (absolute) gpu 0
# so it puts a global lock on gpu 0 with file /tmp/sockeye.gpu0.lock
# -----
# Job 2 on same machine, separate process, cluster assigns GPU 3
export CUDA_VISIBLE_DEVICES=3
python -m sockeye.train .... --device-ids 0
# Without locking, this sockeye process would grab gpu 3 and work fine
# but it thinks it's grabbing absolute gpu 0 and sees that gpu 0 is locked
# (/tmp/sockeye.gpu0.lock) so it fails.
```
In other words, when `CUDA_VISIBLE_DEVICES` is set, sockeye still behaves as if it is receiving an absolute/global gpu id, when in fact the gpu ids have been renumbered locally with respect to that process. This results in a incorrect lock placement.

The current workaround I see is for users who set `CUDA_VISIBLE_DEVICES` to also run with the `--disable-device-locking` flag; a nicer fix would involve sockeye device locking checking `CUDA_VISIBLE_DEVICES` to back-compute the absolute gpu id from it's local/relative gpu id, in order to correctly number the global lock. I _think_ it would look something like this:

```
# Example 1:
# local sockeye gpu id: 0
# CUDA_VISIBLE_DEVICES=3
# sockeye places global lock on gpu 3
# -----
# Example 2:
# local sockeye gpu ids: 1,2
# CUDA_VISIBLE_DEVICES=3,5,0,2
# sockeye places global lock on gpus 5 and 0
# -----
# Example 3:
# local sockeye gpu ids: 1,2
# CUDA_VISIBLE_DEVICES is not set
# sockeye places global lock on gpus 1 and 2
```
Thanks for this nice toolkit!

**Comment by tdomhan** [comment] 2018-05-14 09:12
Thanks for brining this up! Sockeye is indeed unaware of CUDA_VISIBLE_DEVICES and assumes the device ids are the absolute ids. In case you know the exact device id you want to use I'd either disable locking via `--device 0 --disable-device-locking` (as you suggested) or directly specify the device id you want to use without using `CUDA_VISIBLE_DEVICES` or have `CUDA_VISIBLE_DEVICES` set to the all devices. To some extend `CUDA_VISIBLE_DEVICES` fulfills the same purpose as device locking in Sockeye, namely to make sure no two trainings run on the same device.

Maybe for the time being we could add a warning if locking is enabled and `CUDA_VISIBLE_DEVICES` is set. For the longer term we could think about adding the parsing/mapping logic based on `CUDA_VISIBLE_DEVICES` as you suggested.

**Comment by fhieber** [comment] 2018-05-14 09:25
Agreed that adding a warning would make this dependency explicit. 
As a side note, if you don’t care about the actual (absolute) device id you can use negative integers in Sockeye to request any available device. This mixes well with CUDA_VISIBLE_DEVICE settings as you can start each sockeye process with a different ENV setting but all with ``—device-ids -1``.

**Comment by mjpost** [comment] 2018-05-15 12:47
@rudinger, if you are inclined to contribute this as a PR, the changes you'd need to make are fairly simple:

- [`determine_context()` in `train.py`](https://github.com/awslabs/sockeye/blob/ec143fbe285314cd3c1f8099db67f338f3a53d7a/sockeye/train.py#L154)
- [`_setup_context()` in `translate.py`](https://github.com/awslabs/sockeye/blob/ec143fbe285314cd3c1f8099db67f338f3a53d7a/sockeye/translate.py#L211)

It looks like these could also be merged and moved to `utils.py` (though some logic is needed for testing since only a single GPU is supported at test time). The existing [`expand_requested_device_ids()`](https://github.com/awslabs/sockeye/blob/ec143fbe285314cd3c1f8099db67f338f3a53d7a/sockeye/utils.py#L479) would be a natural place to add the CUDA environment variable logic.

**Comment by tdomhan** [comment] 2019-01-15 17:12
I will close this issue for now. We are now printing a warning when CUDA_VISIBLE_DEVICES is set. Locking the devices as seen by CUDA after CUDA_VISIBLE_DEVICES has been set seems like the expected behavior. If one doesn't like to use the mapped ids the solutions are turning off the environment variable or disabling locking altogether using `--disable-device-locking`.

**Closed by tdomhan** 2019-01-15 17:12 UTC
